CREATE WAREHOUSE IF NOT EXISTS COVID_ANALYTICS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS COVID_ANALYTICS_DB;

CREATE SCHEMA IF NOT EXISTS COVID_ANALYTICS_DB.RAW_STAGE;
CREATE SCHEMA IF NOT EXISTS COVID_ANALYTICS_DB.ANALYTICS;

CREATE OR REPLACE FILE FORMAT COVID_ANALYTICS_DB.RAW_STAGE.PARQUET_FMT
  TYPE = PARQUET;
