-- Replace YOUR values before running.

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION COVID_S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'YOUR_STORAGE_AWS_ROLE_ARN'
  STORAGE_ALLOWED_LOCATIONS = ('s3://YOUR_BUCKET_NAME/publish/snowflake/');

DESC STORAGE INTEGRATION COVID_S3_INT;

-- After running DESC STORAGE INTEGRATION, capture:
-- 1) STORAGE_AWS_IAM_USER_ARN
-- 2) STORAGE_AWS_EXTERNAL_ID
--
-- Then create / update the AWS IAM trust policy using those returned values.
