USE WAREHOUSE COVID_ANALYTICS_WH;
USE DATABASE COVID_ANALYTICS_DB;
USE SCHEMA RAW_STAGE;

CREATE OR REPLACE STAGE COVID_GOLD_STAGE
  URL = 's3://YOUR_BUCKET_NAME/publish/snowflake/'
  STORAGE_INTEGRATION = COVID_S3_INT
  FILE_FORMAT = COVID_ANALYTICS_DB.RAW_STAGE.PARQUET_FMT;

LIST @COVID_GOLD_STAGE;
