USE WAREHOUSE COVID_ANALYTICS_WH;
USE DATABASE COVID_ANALYTICS_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE DIM_STATE (
  STATE_SK NUMBER,
  STATE_CODE STRING,
  STATE_NAME STRING,
  REGION STRING,
  IS_TERRITORY BOOLEAN
);

CREATE OR REPLACE TABLE DIM_DATE (
  DATE_SK NUMBER,
  CALENDAR_DATE DATE,
  YEAR NUMBER,
  QUARTER NUMBER,
  MONTH NUMBER,
  DAY_OF_MONTH NUMBER,
  WEEK_OF_YEAR NUMBER,
  DAY_NAME STRING
);

CREATE OR REPLACE TABLE FACT_COVID_STATE_WEEKLY (
  STATE_SK NUMBER,
  DATE_SK NUMBER,
  STATE_CODE STRING,
  REPORT_DATE DATE,
  NEW_CASES NUMBER,
  NEW_DEATHS NUMBER,
  LOAD_TIMESTAMP TIMESTAMP_NTZ,
  CASES_ROLLING_4WK NUMBER,
  DEATHS_ROLLING_4WK NUMBER
);

CREATE OR REPLACE TABLE KPI_LATEST_NATIONAL_SNAPSHOT (
  SNAPSHOT_DATE DATE,
  TOTAL_NEW_CASES NUMBER,
  TOTAL_NEW_DEATHS NUMBER,
  TOTAL_CASES_ROLLING_4WK NUMBER,
  TOTAL_DEATHS_ROLLING_4WK NUMBER,
  STATE_COUNT NUMBER
);

CREATE OR REPLACE TABLE TOP10_STATES_LATEST_CASES (
  REPORT_DATE DATE,
  STATE_CODE STRING,
  STATE_NAME STRING,
  NEW_CASES NUMBER,
  NEW_DEATHS NUMBER,
  CASES_ROLLING_4WK NUMBER,
  DEATHS_ROLLING_4WK NUMBER
);
