USE WAREHOUSE COVID_ANALYTICS_WH;
USE DATABASE COVID_ANALYTICS_DB;
USE SCHEMA ANALYTICS;

COPY INTO DIM_STATE
FROM @COVID_ANALYTICS_DB.RAW_STAGE.COVID_GOLD_STAGE/dim_state/
FILE_FORMAT = (FORMAT_NAME = COVID_ANALYTICS_DB.RAW_STAGE.PARQUET_FMT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO DIM_DATE
FROM @COVID_ANALYTICS_DB.RAW_STAGE.COVID_GOLD_STAGE/dim_date/
FILE_FORMAT = (FORMAT_NAME = COVID_ANALYTICS_DB.RAW_STAGE.PARQUET_FMT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO FACT_COVID_STATE_WEEKLY
FROM @COVID_ANALYTICS_DB.RAW_STAGE.COVID_GOLD_STAGE/fact_covid_state_weekly/
FILE_FORMAT = (FORMAT_NAME = COVID_ANALYTICS_DB.RAW_STAGE.PARQUET_FMT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO KPI_LATEST_NATIONAL_SNAPSHOT
FROM @COVID_ANALYTICS_DB.RAW_STAGE.COVID_GOLD_STAGE/kpi_latest_national_snapshot/
FILE_FORMAT = (FORMAT_NAME = COVID_ANALYTICS_DB.RAW_STAGE.PARQUET_FMT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO TOP10_STATES_LATEST_CASES
FROM @COVID_ANALYTICS_DB.RAW_STAGE.COVID_GOLD_STAGE/top10_states_latest_cases/
FILE_FORMAT = (FORMAT_NAME = COVID_ANALYTICS_DB.RAW_STAGE.PARQUET_FMT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
