USE WAREHOUSE COVID_ANALYTICS_WH;
USE DATABASE COVID_ANALYTICS_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW VW_STATE_WEEKLY_TREND AS
SELECT
  f.REPORT_DATE,
  f.STATE_CODE,
  s.STATE_NAME,
  s.REGION,
  f.NEW_CASES,
  f.NEW_DEATHS,
  f.CASES_ROLLING_4WK,
  f.DEATHS_ROLLING_4WK
FROM FACT_COVID_STATE_WEEKLY f
LEFT JOIN DIM_STATE s
  ON f.STATE_SK = s.STATE_SK;

CREATE OR REPLACE VIEW VW_LATEST_TOP_STATES AS
SELECT *
FROM TOP10_STATES_LATEST_CASES
ORDER BY CASES_ROLLING_4WK DESC, NEW_CASES DESC;
