USE WAREHOUSE COVID_ANALYTICS_WH;
USE DATABASE COVID_ANALYTICS_DB;
USE SCHEMA ANALYTICS;

SELECT COUNT(*) AS dim_state_count FROM DIM_STATE;
SELECT COUNT(*) AS dim_date_count FROM DIM_DATE;
SELECT COUNT(*) AS fact_count FROM FACT_COVID_STATE_WEEKLY;

SELECT * FROM KPI_LATEST_NATIONAL_SNAPSHOT;

SELECT *
FROM TOP10_STATES_LATEST_CASES
ORDER BY CASES_ROLLING_4WK DESC, NEW_CASES DESC;

SELECT REPORT_DATE, SUM(NEW_CASES) AS TOTAL_NEW_CASES
FROM FACT_COVID_STATE_WEEKLY
GROUP BY REPORT_DATE
ORDER BY REPORT_DATE DESC
LIMIT 12;
